version: '3.4'

networks:
   spabookingapis:  

services:
  spabooking-business-db: 
    container_name: spa_booking_business_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8083:1433
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ABC@123456
    networks:
      - spabookingapis
  business-webapi:
    container_name: business-container
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI\Dockerfile
    ports:
      - 4021:80
    depends_on: 
      - spabooking-business-db
    networks:
      - spabookingapis