// <auto-generated />
using System;
using Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SpaBookingDBContext))]
    [Migration("20230515173212_UpdateAuthorize")]
    partial class UpdateAuthorize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BussinessObject.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BussinessObject.Models.Appointment", b =>
                {
                    b.Property<long>("appointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("appointmentId"));

                    b.Property<long?>("customer_IdcustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("room_IdroomId")
                        .HasColumnType("bigint");

                    b.Property<long?>("staff_IdstaffId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("appointmentId");

                    b.HasIndex("customer_IdcustomerId");

                    b.HasIndex("room_IdroomId");

                    b.HasIndex("staff_IdstaffId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("BussinessObject.Models.Appointment_Detail", b =>
                {
                    b.Property<long>("appointmentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("appointmentDetailId"));

                    b.Property<long>("appointment_IdappointmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("service_IdserviceId")
                        .HasColumnType("bigint");

                    b.HasKey("appointmentDetailId");

                    b.HasIndex("appointment_IdappointmentId");

                    b.HasIndex("service_IdserviceId");

                    b.ToTable("AppointmentDetail");
                });

            modelBuilder.Entity("BussinessObject.Models.Customer", b =>
                {
                    b.Property<long>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("customerId"));

                    b.Property<string>("accountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("customerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerId");

                    b.HasIndex("accountId")
                        .IsUnique()
                        .HasFilter("[accountId] IS NOT NULL");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("BussinessObject.Models.Discount", b =>
                {
                    b.Property<long>("discountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("discountId"));

                    b.Property<double>("discountAmount")
                        .HasColumnType("float");

                    b.Property<long>("discountCode")
                        .HasColumnType("bigint");

                    b.Property<int>("discountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("expireDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("service_IdserviceId")
                        .HasColumnType("bigint");

                    b.HasKey("discountId");

                    b.HasIndex("service_IdserviceId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("BussinessObject.Models.Payment", b =>
                {
                    b.Property<long>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("paymentId"));

                    b.Property<long>("appointmentId")
                        .HasColumnType("bigint");

                    b.Property<double>("paymentAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("paymentId");

                    b.HasIndex("appointmentId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("BussinessObject.Models.Review", b =>
                {
                    b.Property<long>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("reviewId"));

                    b.Property<long>("customer_IdcustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("reviewContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reviewRate")
                        .HasColumnType("int");

                    b.Property<long>("service_IdserviceId")
                        .HasColumnType("bigint");

                    b.Property<long>("staff_IdstaffId")
                        .HasColumnType("bigint");

                    b.HasKey("reviewId");

                    b.HasIndex("customer_IdcustomerId");

                    b.HasIndex("service_IdserviceId");

                    b.HasIndex("staff_IdstaffId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("BussinessObject.Models.Room", b =>
                {
                    b.Property<long>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("roomId"));

                    b.Property<string>("roomDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roomStatus")
                        .HasColumnType("int");

                    b.Property<long>("spa_IdspaId")
                        .HasColumnType("bigint");

                    b.HasKey("roomId");

                    b.HasIndex("spa_IdspaId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("BussinessObject.Models.Service", b =>
                {
                    b.Property<long>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("serviceId"));

                    b.Property<string>("serviceDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("servicePrice")
                        .HasColumnType("float");

                    b.HasKey("serviceId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("BussinessObject.Models.Spa", b =>
                {
                    b.Property<long>("spaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("spaId"));

                    b.Property<string>("spaAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spaEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spaPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("spaId");

                    b.ToTable("Spa");
                });

            modelBuilder.Entity("BussinessObject.Models.Staff", b =>
                {
                    b.Property<long>("staffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("staffId"));

                    b.Property<string>("accountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("spa_IdspaId")
                        .HasColumnType("bigint");

                    b.Property<string>("staffEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staffId");

                    b.HasIndex("accountId")
                        .IsUnique()
                        .HasFilter("[accountId] IS NOT NULL");

                    b.HasIndex("spa_IdspaId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BussinessObject.Models.Appointment", b =>
                {
                    b.HasOne("BussinessObject.Models.Customer", "customer_Id")
                        .WithMany("Appointments")
                        .HasForeignKey("customer_IdcustomerId");

                    b.HasOne("BussinessObject.Models.Room", "room_Id")
                        .WithMany("Appointments")
                        .HasForeignKey("room_IdroomId");

                    b.HasOne("BussinessObject.Models.Staff", "staff_Id")
                        .WithMany("Appointments")
                        .HasForeignKey("staff_IdstaffId");

                    b.Navigation("customer_Id");

                    b.Navigation("room_Id");

                    b.Navigation("staff_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Appointment_Detail", b =>
                {
                    b.HasOne("BussinessObject.Models.Appointment", "appointment_Id")
                        .WithMany()
                        .HasForeignKey("appointment_IdappointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Service", "service_Id")
                        .WithMany("appointmentDetails")
                        .HasForeignKey("service_IdserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appointment_Id");

                    b.Navigation("service_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Customer", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", "account_Id")
                        .WithOne("customer_Id")
                        .HasForeignKey("BussinessObject.Models.Customer", "accountId");

                    b.Navigation("account_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Discount", b =>
                {
                    b.HasOne("BussinessObject.Models.Service", "service_Id")
                        .WithMany("Discounts")
                        .HasForeignKey("service_IdserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("service_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Payment", b =>
                {
                    b.HasOne("BussinessObject.Models.Appointment", "appointment_Id")
                        .WithOne("payment_Id")
                        .HasForeignKey("BussinessObject.Models.Payment", "appointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appointment_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Review", b =>
                {
                    b.HasOne("BussinessObject.Models.Customer", "customer_Id")
                        .WithMany("Reviews")
                        .HasForeignKey("customer_IdcustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Service", "service_Id")
                        .WithMany("Reviews")
                        .HasForeignKey("service_IdserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Staff", "staff_Id")
                        .WithMany("Reviews")
                        .HasForeignKey("staff_IdstaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer_Id");

                    b.Navigation("service_Id");

                    b.Navigation("staff_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Room", b =>
                {
                    b.HasOne("BussinessObject.Models.Spa", "spa_Id")
                        .WithMany("Rooms")
                        .HasForeignKey("spa_IdspaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spa_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Staff", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", "account_Id")
                        .WithOne("staff_Id")
                        .HasForeignKey("BussinessObject.Models.Staff", "accountId");

                    b.HasOne("BussinessObject.Models.Spa", "spa_Id")
                        .WithMany("Staffs")
                        .HasForeignKey("spa_IdspaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account_Id");

                    b.Navigation("spa_Id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BussinessObject.Models.Account", b =>
                {
                    b.Navigation("customer_Id");

                    b.Navigation("staff_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Appointment", b =>
                {
                    b.Navigation("payment_Id");
                });

            modelBuilder.Entity("BussinessObject.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BussinessObject.Models.Room", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BussinessObject.Models.Service", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Reviews");

                    b.Navigation("appointmentDetails");
                });

            modelBuilder.Entity("BussinessObject.Models.Spa", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("BussinessObject.Models.Staff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
