version: '3.4'

networks:
   spabookingapis:  

services:
  spabooking-authenticate-db: 
    container_name: spa_booking_authentication_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8082:1433
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ABC@123456
    networks:
      - spabookingapis
  authenticate-webapi:
    container_name: authenticate-container
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI\Dockerfile
    ports:
      - 4020:80
    depends_on: 
      - spabooking-authenticate-db
    networks:
      - spabookingapis



