version: '3.4'
networks:
   spabookingapis:  
services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7208:80
    networks:
      - spabookingapis
